In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/amazon_ecommerce_1M.csv")

/tmp/ipykernel_1309/1289923258.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/content/amazon_ecommerce_1M.csv")

In [4]:
df.shape

(377482, 20)

In [5]:
df.head()

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43.0,71.0,S2679,4.3,2025-03-04,6.0,Bangalore,Tablet,UPI,True,Returned
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13.0,119.0,S9279,4.9,2025-12-12,1.0,Delhi,Tablet,UPI,True,Returned
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46.0,229.0,S5557,4.9,2024-04-25,1.0,Chennai,Mobile App,Credit Card,True,Returned
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6.0,52.0,S2519,3.1,2025-12-18,2.0,Mumbai,Web,UPI,False,In Transit
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48.0,274.0,S3045,2.6,2024-05-16,5.0,Delhi,Web,UPI,False,Delayed

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377482 entries, 0 to 377481
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   user_id             377482 non-null  object
 1   product_id          377482 non-null  object
 2   category            377482 non-null  object
 3   subcategory         377482 non-null  object
 4   brand               377482 non-null  object
 5   price               377481 non-null  float64
 6   discount            377481 non-null  float64
 7   final_price         377481 non-null  float64
 8   rating              377481 non-null  float64
 9   review_count        377481 non-null  float64
 10  stock               377481 non-null  float64
 11  seller_id           377481 non-null  object
 12  seller_rating       377481 non-null  float64
 13  purchase_date       377481 non-null  object
 14  shipping_time_days  377481 non-null  float64
 15  location            377481 non-null  object
 16  device              377481 non-null  object
 17  payment_method      377481 non-null  object
 18  is_returned         377481 non-null  object
 19  delivery_status     377481 non-null  object
dtypes: float64(8), object(12)
memory usage: 57.6+ MB

In [8]:
df

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43.0,71.0,S2679,4.3,2025-03-04,6.0,Bangalore,Tablet,UPI,True,Returned
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13.0,119.0,S9279,4.9,2025-12-12,1.0,Delhi,Tablet,UPI,True,Returned
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46.0,229.0,S5557,4.9,2024-04-25,1.0,Chennai,Mobile App,Credit Card,True,Returned
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6.0,52.0,S2519,3.1,2025-12-18,2.0,Mumbai,Web,UPI,False,In Transit
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48.0,274.0,S3045,2.6,2024-05-16,5.0,Delhi,Web,UPI,False,Delayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377477,U375768,P99417,Clothing,Women,Nike,4672.73,42.88,2669.16,3.3,89.0,185.0,S2493,4.8,2025-09-25,6.0,Chennai,Web,Debit Card,False,Delayed
377478,U989054,P55719,Beauty,Makeup,Lenovo,4086.40,13.78,3523.32,4.1,5.0,319.0,S6103,2.8,2024-07-19,5.0,Mumbai,Tablet,Debit Card,False,Delivered
377479,U872935,P74069,Sports,Cycling,H&M,2540.74,44.44,1411.73,3.4,27.0,376.0,S4998,4.2,2024-05-31,2.0,Mumbai,Mobile App,Credit Card,False,In Transit
377480,U245345,P23501,Electronics,Mobile,LG,45488.54,18.76,36954.87,4.2,15.0,376.0,S9446,3.2,2024-07-19,2.0,Chennai,Web,UPI,False,In Transit
377481,U528578,P66287,Sports,Cycling,App,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.columns

Index(['user_id', 'product_id', 'category', 'subcategory', 'brand', 'price',
       'discount', 'final_price', 'rating', 'review_count', 'stock',
       'seller_id', 'seller_rating', 'purchase_date', 'shipping_time_days',
       'location', 'device', 'payment_method', 'is_returned',
       'delivery_status'],
      dtype='object')

In [10]:
df["brand"]

0             H&M
1         Samsung
2             H&M
3            Sony
4            Sony
           ...
377477       Nike
377478     Lenovo
377479        H&M
377480         LG
377481        App
Name: brand, Length: 377482, dtype: object

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.isnull().sum()

user_id               0
product_id            0
category              0
subcategory           0
brand                 0
price                 1
discount              1
final_price           1
rating                1
review_count          1
stock                 1
seller_id             1
seller_rating         1
purchase_date         1
shipping_time_days    1
location              1
device                1
payment_method        1
is_returned           1
delivery_status       1
dtype: int64

# To remove extra space

In [18]:
text_columns = df.select_dtypes(include=['object']).columns
df[text_columns] = df[text_columns].apply(lambda x: x.str.strip())

AttributeError: Can only use .str accessor with string values!

# Y its not work column contain a mixture of strings, numbers, or other values

In [19]:
text_columns = df.select_dtypes(include=['object']).columns
df[text_columns] = df[text_columns].apply(
    lambda x: x.map(lambda value: value.strip() if isinstance(value, str) else value))

In [20]:
df.describe()

,price,discount,final_price,rating,review_count,stock,seller_rating,shipping_time_days
count,377481.000000,377481.000000,377481.000000,377481.000000,377481.000000,377481.000000,377481.000000,377481.000000
mean,13211.049962,28.994275,9934.028425,3.926740,32.515788,250.030587,3.750151,3.169521
std,18053.413556,14.701836,14269.597246,0.519905,42.939782,144.631747,0.722906,1.672933
min,200.080000,5.000000,102.900000,1.600000,0.000000,0.000000,2.500000,1.000000
25%,2707.790000,16.900000,1708.930000,3.600000,10.000000,125.000000,3.100000,2.000000
50%,4974.550000,28.070000,3798.570000,3.900000,20.000000,250.000000,3.800000,3.000000
75%,14137.790000,39.280000,10387.320000,4.300000,39.000000,375.000000,4.400000,5.000000
max,79998.740000,70.000000,75831.110000,5.000000,1521.000000,500.000000,5.000000,6.000000

In [21]:
df['rating'].min(), df['rating'].max()

(1.6, 5.0)

In [15]:
df.dtypes

user_id                object
product_id             object
category               object
subcategory            object
brand                  object
price                 float64
discount              float64
final_price           float64
rating                float64
review_count          float64
stock                 float64
seller_id              object
seller_rating         float64
purchase_date          object
shipping_time_days    float64
location               object
device                 object
payment_method         object
is_returned            object
delivery_status        object
dtype: object

# convert purchase_date dtypes

In [22]:
df["purchase_date"] = pd.to_datetime(df["purchase_date"])

In [23]:
df.dtypes

user_id                       object
product_id                    object
category                      object
subcategory                   object
brand                         object
price                        float64
discount                     float64
final_price                  float64
rating                       float64
review_count                 float64
stock                        float64
seller_id                     object
seller_rating                float64
purchase_date         datetime64[ns]
shipping_time_days           float64
location                      object
device                        object
payment_method                object
is_returned                   object
delivery_status               object
dtype: object

In [24]:
df.to_csv("amazon_ecommerce_1M.csv", index=False)

In [25]:
from google.colab import files
files.download("amazon_ecommerce_1M.csv")