In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df=pd.read_excel("/content/NESTLE SALES DATASET.xlsx")

In [4]:
df.shape

(18116, 8)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18116 entries, 0 to 18115
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  18116 non-null  object
 1   Unnamed: 1  18116 non-null  object
 2   Unnamed: 2  18116 non-null  object
 3   Unnamed: 3  18116 non-null  object
 4   Unnamed: 4  18116 non-null  object
 5   Unnamed: 5  18116 non-null  object
 6   Unnamed: 6  18116 non-null  object
 7   Unnamed: 7  18116 non-null  object
dtypes: object(8)
memory usage: 1.1+ MB

In [8]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
18111    False
18112    False
18113    False
18114    False
18115    False
Length: 18116, dtype: bool

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.isnull()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
18111,False,False,False,False,False,False,False,False
18112,False,False,False,False,False,False,False,False
18113,False,False,False,False,False,False,False,False
18114,False,False,False,False,False,False,False,False
18115,False,False,False,False,False,False,False,False

In [12]:
df.isnull().sum()

Unnamed: 0    0
Unnamed: 1    0
Unnamed: 2    0
Unnamed: 3    0
Unnamed: 4    0
Unnamed: 5    0
Unnamed: 6    0
Unnamed: 7    0
dtype: int64

In [13]:
df.dtypes

Unnamed: 0    object
Unnamed: 1    object
Unnamed: 2    object
Unnamed: 3    object
Unnamed: 4    object
Unnamed: 5    object
Unnamed: 6    object
Unnamed: 7    object
dtype: object